### ISSUE TITLE
Reference to wrong icons

### ISSUE THREAD

**Issue by gjportegies** [EmicoEcommerce/Magento2TweakwiseHyva-archived#1]
In the search-form.phtml file there is a reference to the custom theme icon class of Zitmaxx:

```use Zitmaxx\ThemeIcons\ViewModel\ThemeIcons;```

This should probably be one of the default icon classes `HeroiconsSolid` or `HeroiconsOutline`.

**Comment by bramstroker** [comment]
Hi Guus, thanks for you attention. My colleague Iris is currenctly cleaning up the templates.
I'll let you know when it is done. Than you can do another review as you'd like.

**Comment by gjportegies** [comment]
@bramstroker awesome! I'll check it out when Iris is done.

**Comment by podenemus** [comment]
Hi @gjportegies!

Thanks for reaching out. We did some fixes yesterday and some more today, removing all project specific code (including the Zitmaxx icons reference)

Our next steps will be setting up a clean demo environment and do some more testing. First stable release is planned for the second week of 2022. We'll also update the Hyva tracker when the release is ready. In the mean time, feel free to review the code, any feedback is highly appreciated.

Have a wonderful Christmas!
