### ISSUE TITLE
Grouped and bundle products have zero price in a quick search popup

### ISSUE THREAD

**Issue by epolish** [EmicoEcommerce/Magento2TweakwiseHyva-archived#24]
### Expected behaviour
Grouped and bundle products have a correct price in a quick search popup

### Actual behaviour
Grouped and bundle products have zero price

### Why?
There are two issues:

`\Emico\Tweakwise\Model\Autocomplete\DataProvider\ProductItem::toArray`

```php
/**
 * @return array
 */
public function toArray(): array
{
    $product = $this->product;
    $price = $product->getPriceInfo();
    $image = $this->getImage();

    return [
        'title' => $this->getTitle(),
        'url' => $product->getProductUrl(),
        'image' => $image->getImageUrl(),
        'price' => (float) $price->getPrice('regular_price')->getValue(),
        'final_price' => (float) $price->getPrice('final_price')->getValue(),
        'type' => 'product',
        'row_class' => 'qs-option-product',
    ];
}
```

This method above cannot be used for all product types such as bundle and grouped ones as they have different pricing calculations strategies;
Actually, these product items are populated in the next method call

`\Emico\Tweakwise\Model\Autocomplete\DataProviderHelper::getProductItems`

Via $productCollection - but, this approach (using collections) uses price index tables to speed up the request processing and not to calculate all the prices during the request which is common. And, this price index table is populated by a default magento price indexer. And that's what happens during the grouped products price generation (it's a default magento code)

`\Magento\GroupedProduct\Model\ResourceModel\Product\Indexer\Price\Grouped::prepareGroupedProductPriceDataSelect`
```php
...

$select->join(
    ['i' => $this->getMainTable($dimensions)],
    'i.entity_id = l.linked_product_id',
    [
        'tax_class_id' => $taxClassId,
        'price' => new \Zend_Db_Expr('NULL'),
        'final_price' => new \Zend_Db_Expr('NULL'),
        'min_price' => new \Zend_Db_Expr('MIN(' . $minCheckSql . ')'),
        'max_price' => new \Zend_Db_Expr('MAX(' . $maxCheckSql . ')'),
        'tier_price' => new \Zend_Db_Expr('NULL'),
    ]
);
...
```

As we can see a price and a final_price are set to NULL in the core Magento code.
And if you run this SQL query you'll see empty price & final_price columns
*15079 is an example id of one of some grouped products

```sql
SELECT * FROM catalog_product_index_price_replica WHERE entity_id = 15079 
```

As for the bundle products the way of getting a price and a regular price should be also different, something like this
*We should be cautious of using this functions as they do some extra SQL queries per a product

```php
$price->getPrice('final_price')->getMinimalPrice()->getValue()
$price->getPrice('regular_price')->getMinimalPrice()->getValue()
```

So the source code should be reworked according to Magento price model flows

`\Emico\Tweakwise\Model\Autocomplete\DataProvider\ProductItem::toArray`

### Versions

- Magento 2.4.3-p1
- Tweakwise 4.2.0
- Tweakwise Hyvä 1.0.0

**Comment by ahuininga-orisha** [comment]
Fixed it in the tweakwise repo, since the problem is in the tweakwise plugin itself and not in the hyva compatability module.

It's fixed without adding extra queries. Instead it uses the price from the tweakwise response.

https://github.com/EmicoEcommerce/Magento2Tweakwise/pull/262
